services:
  redis:
    image: redis:latest
    container_name: redis-token
    restart: unless-stopped
    command: [
      "redis-server",
      "--appendonly",
      "yes",
      "--user",
      "$REDIS_USER",
      "on",
      ">$REDIS_PASSWD",
      "~*",
      "+@all",
      "--user",
      "default",
      "off"
    ]
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWD: ${REDIS_PASSWD}
    ports:
      - "${PORT_REDIS}:${PORT_REDIS}"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --user $REDIS_USER -a $REDIS_PASSWD ping | grep -q PONG || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  links_s3_app:
    container_name: links_s3_app
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${PORT_APP}:${PORT_APP}"
    command: ["uv", "run", "delivery-s3-temporary-links"]
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx
      - ./certs:/etc/letsencrypt
    ports:
      - "${PORT_http_NGINX}:${PORT_http_NGINX}"
      - "${PORT_https_NGINX}:${PORT_https_NGINX}"
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
    entrypoint: ""

volumes:
  redis_data:
