services:
  redis:
    image: redis:latest
    container_name: redis-token
    restart: unless-stopped
    command: [
      "redis-server",
      "--appendonly",
      "yes",
      "--user",
      "$REDIS_USER",
      "on",
      ">$REDIS_PASSWD",
      "~*",
      "+@all",
      "--user",
      "default",
      "off"
    ]
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWD: ${REDIS_PASSWD}
    ports:
      - "${PORT_REDIS}:${PORT_REDIS}"
    volumes:
      - redis_data:/data
    networks:
      - links_s3
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --user $REDIS_USER -a $REDIS_PASSWD ping | grep -q PONG || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  links_s3_app:
    container_name: links_s3_app
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${PORT_APP}:${PORT_APP}"
    command: ["uv", "run", "delivery-s3-temporary-links"]
    networks:
      - links_s3
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    restart: on-failure
    environment:
      PORT_HTTP_NGINX: ${PORT_HTTP_NGINX}
      PORT_HTTPS_NGINX: ${PORT_HTTPS_NGINX}
    ports:
      - "${PORT_HTTP_NGINX}:${PORT_HTTP_NGINX}"
      - "${PORT_HTTPS_NGINX}:${PORT_HTTPS_NGINX}"
    depends_on:
      - links_s3_app
    networks:
      - links_s3
    volumes:
      - ./nginx:/etc/nginx
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    container_name: certbot
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
    entrypoint: sh -c
    command: >
      "certbot certonly --webroot -w /var/www/certbot -d $DOMAIN --email $EMAIL --agree-tos --non-interactive;
        while true; do
          certbot renew --webroot -w /var/www/certbot;
          sleep 12h;
        done"
    networks:
      - links_s3
    depends_on:
      - nginx
    volumes:
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  redis_data:

networks:
  links_s3:
