services:
  redis:
    image: redis:latest
    container_name: redis-token
    restart: unless-stopped
    command: [
      "redis-server",
      "--appendonly",
      "yes",
      "--user",
      "$REDIS_USER",
      "on",
      ">$REDIS_PASSWD",
      "~*",
      "+@all",
      "--user",
      "default",
      "off"
    ]
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWD: ${REDIS_PASSWD}
    ports:
      - "${PORT_REDIS}:${PORT_REDIS}"
    volumes:
      - redis_data:/data
    networks:
      - links_s3
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --user $REDIS_USER -a $REDIS_PASSWD ping | grep -q PONG || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  links_s3_app:
    container_name: links_s3_app
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${PORT_APP}:${PORT_APP}"
    command: ["uv", "run", "delivery-s3-temporary-links"]
    networks:
      - links_s3
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    restart: on-failure
    environment:
      PORT_HTTP_NGINX: ${PORT_HTTP_NGINX}
      PORT_HTTPS_NGINX: ${PORT_HTTPS_NGINX}
    ports:
      - "${PORT_HTTP_NGINX}:${PORT_HTTP_NGINX}"
      - "${PORT_HTTPS_NGINX}:${PORT_HTTPS_NGINX}"
    depends_on:
      - certbot
      - links_s3_app
    networks:
      - links_s3
    volumes:
      - ./nginx:/etc/nginx
      - ./certs:/etc/letsencrypt

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    container_name: certbot
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
    entrypoint: /bin/sh
    command: -c "while true; do certbot renew --nginx; sleep 12h; done"
    networks:
      - links_s3
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d

volumes:
  redis_data:

networks:
  links_s3:
