[project]
name = "delivery-s3-temporary-links"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arduinum628", email = "message.chaos628@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "boto3>=1.42.45",
    "fastapi>=0.128.7",
    "granian>=2.7.1",
    "mypy-boto3-s3>=1.42.37",
    "passlib>=1.7.4",
    "pydantic-settings>=2.13.1",
    "pyjwt>=2.11.0",
    "redis>=7.1.1",
]

[project.scripts]
delivery-s3-temporary-links = "delivery_s3_temporary_links.run_app:run"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
