buckets:
  - name: bucketname1
    folders:
      - name: foldername1
        status: private
      - name: foldername2
        status: public

  - name: bucketname2
    folders:
      - name: foldername1
        status: private
      - name: foldername2
        status: public

users:
  - username: "name_user"
    passwd: "user_passwd"

  - username: "name_user"
    passwd: "user_passwd"
