buckets:
  name-bucket_1:
    folder:
      example_1:
        status: private
      example_2:
        status: public
  name-bucket_2:
    folder:
      example_1:
        status: private
      example_2:
        status: public
